version: '3.8'

services:
  app:
    build: .
    container_name: fashion-muse-studio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - fashion-muse-network

  db:
    image: postgres:15-alpine
    container_name: fashion-muse-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fashion_muse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fashionmuse123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - fashion-muse-network

  nginx:
    image: nginx:alpine
    container_name: fashion-muse-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - app
    networks:
      - fashion-muse-network

  redis:
    image: redis:7-alpine
    container_name: fashion-muse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fashion-muse-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  fashion-muse-network:
    driver: bridge